Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
Loading training set...
==> use shapenet dataset
==> use shapenet folder number 0
==> use image path: 3dgan_data_split/shapenet_car, num images: 0
Traceback (most recent call last):
  File "train_3d.py", line 337, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train_3d.py", line 331, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 49, in subprocess_fn
    training_loop_3d.training_loop(rank=rank, **c)
  File "/home/windows-ssh/git/GET3D/training/training_loop_3d.py", line 134, in training_loop
    training_set_sampler = misc.InfiniteSampler(
  File "/home/windows-ssh/git/GET3D/torch_utils/misc.py", line 120, in __init__
    assert len(dataset) > 0
AssertionError
